import { useEffect, useMemo, useState } from "react";
import { Panel } from "../components/Panel";
import { downloadFile } from "../lib/materialListExport";
import {
  analyzeDoctrine, createDoctrine, deleteDoctrineFit, formatQty, formatVolume,
  importDoctrineEftFile, importDoctrineEftFolder, importDoctrineEftText,
  listDoctrineFits, listDoctrines, setDoctrineFitQuantity, updateDoctrine,
  type Doctrine, type DoctrineAnalysis, type DoctrineFit, type DoctrineInput,
  type DoctrineItem, type QuartermasterExports, type ShoppingLine,
} from "../lib/backend";

type ActionFilter = "ACTIONABLE" | "ALL" | "READY" | "BUILD" | "BUY" | "BLOCKED";
type DemandSort = "ACTION" | "ITEM" | "REQUIRED" | "MISSING" | "COST" | "VOLUME";
const blank: DoctrineInput = { name: "", description: "", category: "General", fleetNotes: "", isActive: true, version: 1 };
const isk = (value: number | null) => value == null ? "Unpriced" : `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })} ISK`;
const priority = (action: string) => ({ BLOCKED: 0, BUY: 1, BUILD: 2, READY: 3 }[action] ?? 4);
const lineSummary = (lines: ShoppingLine[]) => ({
  types: lines.length,
  units: lines.reduce((sum, line) => sum + line.shortageQuantity, 0),
  cost: lines.reduce((sum, line) => sum + (line.totalAcquisitionCost ?? 0), 0),
  volume: lines.reduce((sum, line) => sum + (line.totalVolumeM3 ?? 0), 0),
  unpriced: lines.filter(line => line.totalAcquisitionCost == null).length,
});

export function QuartermasterPage() {
  const [doctrines, setDoctrines] = useState<Doctrine[]>([]), [selected, setSelected] = useState<number | null>(null);
  const [draft, setDraft] = useState<DoctrineInput>(blank), [editing, setEditing] = useState(false);
  const [fits, setFits] = useState<DoctrineFit[]>([]), [analysis, setAnalysis] = useState<DoctrineAnalysis | null>(null);
  const [eft, setEft] = useState(""), [path, setPath] = useState(""), [error, setError] = useState<string | null>(null), [feedback, setFeedback] = useState<string | null>(null), [working, setWorking] = useState(false);
  const [actionFilter, setActionFilter] = useState<ActionFilter>("ACTIONABLE"), [kindFilter, setKindFilter] = useState("ALL"), [search, setSearch] = useState(""), [sort, setSort] = useState<DemandSort>("ACTION");

  async function refresh(prefer?: number) {
    const rows = await listDoctrines(); setDoctrines(rows);
    const id = prefer ?? selected ?? rows[0]?.doctrineId ?? null; setSelected(id);
    if (!id) { setFits([]); setEditing(true); return; }
    const doctrine = rows.find(row => row.doctrineId === id);
    if (doctrine) setDraft({ name: doctrine.name, description: doctrine.description, category: doctrine.category, fleetNotes: doctrine.fleetNotes, isActive: doctrine.isActive, version: doctrine.version });
    setFits(await listDoctrineFits(id));
  }
  useEffect(() => { refresh().catch(reason => setError(String(reason))); }, []);
  async function run(action: () => Promise<void>) { setWorking(true); setError(null); setFeedback(null); try { await action(); } catch (reason) { setError(String(reason)); } finally { setWorking(false); } }
  async function choose(id: number) { setSelected(id); setAnalysis(null); setEditing(false); const doctrine = doctrines.find(row => row.doctrineId === id)!; setDraft({ name: doctrine.name, description: doctrine.description, category: doctrine.category, fleetNotes: doctrine.fleetNotes, isActive: doctrine.isActive, version: doctrine.version }); setFits(await listDoctrineFits(id)); }
  async function analyze() { if (selected) await run(async () => { setAnalysis(await analyzeDoctrine(selected)); setActionFilter("ACTIONABLE"); setFeedback("Doctrine analysis refreshed"); }); }
  async function copy(label: string, text: string) { try { await navigator.clipboard.writeText(text); setFeedback(`${label} copied`); } catch (reason) { setError(`${label} could not be copied: ${String(reason)}`); } }
  const field = (key: keyof DoctrineInput, label: string) => <label className="new-op-field"><span className="ops-field-label">{label}</span><input className="sd-path-input" value={String(draft[key])} onChange={event => setDraft(value => ({ ...value, [key]: key === "version" ? Number(event.target.value) : event.target.value }))} /></label>;

  const visibleItems = useMemo(() => {
    if (!analysis) return [];
    const term = search.trim().toLowerCase();
    return analysis.items.filter(item => {
      const action = actionFilter === "ALL" || (actionFilter === "ACTIONABLE" ? item.action !== "READY" : item.action === actionFilter);
      const kind = kindFilter === "ALL" || item.itemKind === kindFilter;
      const text = !term || `${item.itemName} ${item.blockedReason ?? ""} ${item.blockedDetail ?? ""}`.toLowerCase().includes(term);
      return action && kind && text;
    }).sort((a, b) => sort === "ITEM" ? a.itemName.localeCompare(b.itemName) : sort === "REQUIRED" ? b.required - a.required : sort === "MISSING" ? b.missing - a.missing : sort === "COST" ? (b.purchaseCost ?? -1) - (a.purchaseCost ?? -1) : sort === "VOLUME" ? (b.totalMissingVolumeM3 ?? -1) - (a.totalMissingVolumeM3 ?? -1) : priority(a.action) - priority(b.action) || a.itemName.localeCompare(b.itemName));
  }, [analysis, actionFilter, kindFilter, search, sort]);

  return <div className="dash qm-page">
    {error && <div className="sd-error"><div className="conflict-desc">{error}</div></div>}{feedback && <div className="data-source">{feedback}</div>}
    <div className="qm-command-layout">
      <div className="qm-doctrine-zone">
        <Panel title="Doctrine Setup" keel="furnace">
          <div className="new-op-mode-toggle qm-doctrine-tabs">{doctrines.map(doctrine => <button key={doctrine.doctrineId} className={selected === doctrine.doctrineId ? "target-select enabled active" : "target-select enabled"} onClick={() => choose(doctrine.doctrineId)}>{doctrine.name} · v{doctrine.version}</button>)}</div>
          {!editing && selected ? <div className="qm-doctrine-summary"><div className="inv-name">{draft.name}</div><div><span>Category</span>{draft.category}</div><div><span>Version</span>{draft.version}</div><div><span>Active</span>{draft.isActive ? "YES" : "NO"}</div><p title={draft.description}>{draft.description || "No description"}</p><p title={draft.fleetNotes}>{draft.fleetNotes || "No fleet notes"}</p><div className="new-op-actions"><button className="target-select enabled" onClick={() => setEditing(true)}>▼ Edit Doctrine</button><button className="target-select enabled" onClick={() => { setSelected(null); setDraft(blank); setFits([]); setAnalysis(null); setEditing(true); }}>New Doctrine</button></div></div> : <div className="qm-doctrine-edit"><div className="manual-inv-form">{field("name", "Doctrine name")}{field("category", "Category")}{field("version", "Version")}</div><label><input type="checkbox" checked={draft.isActive} onChange={event => setDraft(value => ({ ...value, isActive: event.target.checked }))} /> Active</label>{field("description", "Description")}{field("fleetNotes", "Fleet notes")}<div className="new-op-actions"><button className="target-select enabled" disabled={working || !draft.name.trim()} onClick={() => run(async () => { if (selected) { await updateDoctrine(selected, draft); await refresh(selected); setFeedback("Doctrine updated"); } else { const doctrine = await createDoctrine(draft); await refresh(doctrine.doctrineId); setSelected(doctrine.doctrineId); setFeedback("Doctrine created"); } setEditing(false); })}>{selected ? "Save Doctrine" : "Create Doctrine"}</button>{selected && <button className="target-select" onClick={() => setEditing(false)}>Cancel</button>}</div></div>}
        </Panel>

        {selected && <><Panel title="EFT Import" keel="coolant"><textarea className="sd-path-input qm-eft" value={eft} onChange={event => setEft(event.target.value)} placeholder={'[Hull, Fit Name]\nModule\nCharge x1000'} /><input className="sd-path-input" value={path} onChange={event => setPath(event.target.value)} placeholder="EFT file or folder path" /><div className="new-op-actions qm-wrap"><button className="target-select enabled" disabled={working || !eft.trim()} onClick={() => run(async () => { await importDoctrineEftText(selected, eft, "EFT Text"); setEft(""); await refresh(selected); setFeedback("EFT text imported"); })}>Import Text</button><button className="target-select enabled" disabled={working || !path} onClick={() => run(async () => { await importDoctrineEftFile(selected, path); await refresh(selected); setFeedback("EFT file imported"); })}>Import File</button><button className="target-select enabled" disabled={working || !path} onClick={() => run(async () => { const imported = await importDoctrineEftFolder(selected, path); await refresh(selected); setFeedback(`${imported.length} EFT files imported`); })}>Import Folder</button><button className="target-select enabled" disabled={working} onClick={() => run(async () => { const text = await navigator.clipboard.readText(); await importDoctrineEftText(selected, text, "Clipboard"); await refresh(selected); setFeedback("Clipboard EFT imported"); })}>Clipboard</button></div></Panel>
        <Panel title="Fleet Composition" keel="coolant">{fits.length === 0 ? <div className="data-source">No fits imported.</div> : <div className="qm-fit-list"><div className="qm-fit-columns qm-fit-header"><div>Fit</div><div>Hull</div><div>Target</div><div>Readiness / Details</div><div>Actions</div></div>{fits.map(fit => { const ready = analysis?.fits.find(row => row.fitId === fit.fitId); return <details key={fit.fitId} className="qm-fit-row"><summary className="qm-fit-columns"><div><span className="inv-name">{fit.name}</span><span className="bts-result-meta">{fit.sourceName}</span></div><div className="inv-name">{fit.hullName}</div><label className="qm-fit-target"><span>Target</span><input aria-label={`Target quantity for ${fit.name}`} className="sd-path-input" type="number" min="0" value={fit.desiredQuantity} onClick={event => event.stopPropagation()} onChange={event => { const quantity = Number(event.target.value); setFits(rows => rows.map(row => row.fitId === fit.fitId ? { ...row, desiredQuantity: quantity } : row)); }} onBlur={() => run(async () => { await setDoctrineFitQuantity(fit.fitId, fit.desiredQuantity); await refresh(selected); })} /></label><div className="qm-fit-readiness">{ready ? <><span>Ready {ready.readyNow}</span><span>After {ready.readyAfterBuild}</span><span>Missing {ready.stillMissing}</span></> : <span>{fit.items.length} normalized items</span>}<span className="qm-details-cue">▸ Details</span></div><button className="target-select qm-delete-fit" onClick={event => { event.preventDefault(); event.stopPropagation(); run(async () => { await deleteDoctrineFit(fit.fitId); await refresh(selected); setAnalysis(null); }); }}>Delete</button></summary><div className="qm-fit-technical"><div className="data-source">EFT source: {fit.sourceName} · {fit.items.length} normalized item types</div>{fit.items.map(item => <div key={item.typeId}>{item.itemKind}: {item.itemName} × {item.quantity}</div>)}<pre>{fit.originalEftText}</pre></div></details>; })}</div>}<button className="target-select enabled qm-analyze" disabled={working || fits.length === 0} onClick={analyze}>Analyze Doctrine</button></Panel></>}
      </div>

      <main className="qm-right">
        {!analysis ? <Panel title="Fleet Readiness" keel="furnace" className="qm-empty"><div className="data-source">Select a doctrine, set fleet targets, then Analyze Doctrine to calculate readiness, manufacturing, and purchasing.</div></Panel> : <>
          <Panel title="Fleet Readiness" keel={analysis.summary.canFullyField ? "coolant" : "furnace"} className="qm-hero"><div className="qm-hero-title"><span>{analysis.doctrine.name}</span><strong>{analysis.summary.overallStatus}</strong></div><div className="qm-readiness-grid"><Metric label="Target Ships" value={formatQty(analysis.summary.target)} /><Metric label="Ready Now" value={formatQty(analysis.summary.readyNow)} /><Metric label="Ready After Build" value={formatQty(analysis.summary.readyAfterBuild)} /><Metric label="Still Missing" value={formatQty(analysis.summary.stillMissingAfterBuild)} /><Metric label="Coverage Now" value={`${analysis.summary.coverageNowPercent.toFixed(1)}%`} /><Metric label="Coverage After Build" value={`${analysis.summary.coverageAfterBuildPercent.toFixed(1)}%`} /><Metric label="Status" value={analysis.summary.overallStatus} /></div>
            <h3>Cost Summary</h3><div className="qm-metric-row"><Metric label="Buy Cost" value={isk(analysis.summary.buyCost)} /><Metric label="Build Cost" value={isk(analysis.summary.buildInputCost)} /><Metric label={analysis.summary.totalsComplete ? "Total Completion Cost" : "Known Completion Cost"} value={isk(analysis.summary.totalCompletionCost)} /></div>{analysis.summary.partialReasons.length > 0 && <div className="data-source">Partial total · {analysis.summary.excludedLines} excluded: {analysis.summary.partialReasons.map(reason => `${reason.reason} ${reason.count}`).join(" · ")}</div>}
            <h3>Logistics</h3><div className="qm-metric-row"><Metric label="Buy Volume" value={formatVolume(analysis.summary.buyVolumeM3)} /><Metric label="Build Volume" value={formatVolume(analysis.summary.buildInputVolumeM3)} /><Metric label="Total Hauling Volume" value={formatVolume(analysis.summary.totalHaulingVolumeM3)} /></div>
            <h3>Export Actions</h3><div className="qm-export-grid"><ExportRow label="Finished Goods" exports={analysis.shopping.buyFinishedGoods} suffix="finished-goods" selected={selected} copy={copy} /><ExportRow label="Manufacturing Inputs" exports={analysis.shopping.buyManufacturingInputs} suffix="manufacturing-inputs" selected={selected} copy={copy} /><ExportRow label="Combined" exports={analysis.shopping.combinedPurchaseList} suffix="combined" selected={selected} copy={copy} /></div>
          </Panel>

          <Panel title="Fleet Summary" keel="coolant"><div className="inv-table"><div className="inv-row qm-fleet-grid"><div>Fit</div><div>Hull</div><div>Target</div><div>Ready</div><div>After Build</div><div>Missing</div><div>Coverage</div><div>Status</div></div>{analysis.fits.map(fit => <details key={fit.fitId}><summary className="inv-row qm-fleet-grid"><div className="inv-name">{fit.name}</div><div>{fit.hullName}</div><div>{fit.desired}</div><div>{fit.readyNow}</div><div>{fit.readyAfterBuild}</div><div>{fit.stillMissing}</div><div>{fit.coveragePercent.toFixed(1)}%</div><div className={`inv-status ${fit.status === "READY" ? "nominal" : fit.status === "BUILD" ? "coolant" : "alert"}`}>{fit.status}</div></summary><div className="data-source">Fit readiness is calculated from complete hull, module, charge, drone, and cargo requirements.</div></details>)}</div></Panel>

          <Panel title="Aggregated Doctrine Demand" keel="furnace"><div className="qm-action-summary"><Filter label="All" count={analysis.items.length} active={actionFilter === "ALL"} onClick={() => setActionFilter("ALL")} /><Filter label="Ready" count={analysis.summary.actionSummary.readyItemTypes} active={actionFilter === "READY"} onClick={() => setActionFilter("READY")} /><Filter label="Build" count={analysis.summary.actionSummary.buildItemTypes} active={actionFilter === "BUILD"} onClick={() => setActionFilter("BUILD")} /><Filter label="Buy" count={analysis.summary.actionSummary.buyItemTypes} active={actionFilter === "BUY"} onClick={() => setActionFilter("BUY")} /><Filter label="Blocked" count={analysis.summary.actionSummary.blockedItemTypes} active={actionFilter === "BLOCKED"} onClick={() => setActionFilter("BLOCKED")} /></div>{analysis.summary.blockedReasons.length > 0 && <details className="qm-blocked-summary"><summary>Blocked Items: {analysis.summary.actionSummary.blockedItemTypes}</summary>{analysis.summary.blockedReasons.map(reason => <div key={reason.reason}>{reason.reason}: {reason.count}</div>)}</details>}<div className="manual-inv-form qm-demand-controls"><label><span className="ops-field-label">Search</span><input className="sd-path-input" value={search} onChange={event => setSearch(event.target.value)} placeholder="Item or reason" /></label><label><span className="ops-field-label">Action</span><select className="sd-path-input" value={actionFilter} onChange={event => setActionFilter(event.target.value as ActionFilter)}><option value="ACTIONABLE">Build + Buy + Blocked</option><option value="ALL">All</option><option value="READY">Ready</option><option value="BUILD">Build</option><option value="BUY">Buy</option><option value="BLOCKED">Blocked</option></select></label><label><span className="ops-field-label">Kind</span><select className="sd-path-input" value={kindFilter} onChange={event => setKindFilter(event.target.value)}><option value="ALL">All kinds</option>{["Hull", "Module", "Rig", "Subsystem", "Drone", "Charge", "Script", "Cargo"].map(kind => <option key={kind}>{kind}</option>)}</select></label><label><span className="ops-field-label">Sort</span><select className="sd-path-input" value={sort} onChange={event => setSort(event.target.value as DemandSort)}><option value="ACTION">Action</option><option value="ITEM">Item</option><option value="REQUIRED">Required</option><option value="MISSING">Missing</option><option value="COST">Cost</option><option value="VOLUME">Missing m³</option></select></label></div><div className="data-source">{visibleItems.length} result(s) · READY is hidden in the default view.</div>{visibleItems.length === 0 ? <div className="data-source">No demand matches the selected filters.</div> : <DemandTable items={visibleItems} />}</Panel>

          <Panel title="Build Details" keel="coolant"><details><summary>{analysis.buildDetails.length} build item type(s) · {isk(analysis.summary.buildInputCost)} · {formatVolume(analysis.summary.buildInputVolumeM3)}</summary><div className="qm-build-list">{analysis.buildDetails.map(detail => <details key={detail.typeId}><summary className="inv-row qm-build-grid"><div className="inv-name">{detail.itemName}</div><div>{detail.manufacturingRuns} runs</div><div>{isk(detail.rawMaterialCost)}</div><div>{formatVolume(detail.rawMaterialVolumeM3)}</div><div className={`inv-status ${detail.missingBlueprintWarning || detail.unmanufacturableWarning || detail.warnings.length ? "alert" : "coolant"}`}>{detail.missingBlueprintWarning || detail.unmanufacturableWarning || detail.warnings.length ? "BLOCKED" : "BUILD"}</div></summary><div className="data-source">Owner: {detail.blueprintOwner ?? "Unavailable"} · ME {detail.me ?? "—"} · TE {detail.te ?? "—"} · Output {detail.outputQuantity}</div>{detail.missingBlueprintWarning && <div className="sd-error">Missing Blueprint · {detail.missingBlueprintWarning}</div>}{detail.unmanufacturableWarning && <div className="sd-error">{detail.unmanufacturableWarning}</div>}{detail.warnings.map(warning => <div className="sd-error" key={warning}>{warning}</div>)}{detail.rawMaterials.map(material => <div className="inv-row" key={material.typeId} style={{ gridTemplateColumns: "1.4fr .7fr .7fr .8fr .9fr" }}><div>{material.itemName}</div><div>Required {material.requiredQuantity}</div><div>Missing {material.missingQuantity}</div><div>{isk(material.totalAcquisitionCost)}</div><div>{material.marketStatus}</div></div>)}</details>)}</div></details></Panel>

          <Panel title="Purchase Details" keel="furnace"><Purchase label="Finished Goods" lines={analysis.buyLines} /><Purchase label="Manufacturing Inputs" lines={analysis.buildInputLines} /></Panel>
        </>}
      </main>
    </div>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="res-summary-cell"><div className="res-summary-label">{label}</div><div className="ops-field-value">{value}</div></div>; }
function Filter({ label, count, active, onClick }: { label: string; count: number; active: boolean; onClick: () => void }) { return <button className={active ? "target-select enabled active" : "target-select enabled"} onClick={onClick}>{label} {count}</button>; }
function ExportRow({ label, exports, suffix, selected, copy }: { label: string; exports: QuartermasterExports[keyof QuartermasterExports]; suffix: string; selected: number | null; copy: (label: string, text: string) => Promise<void> }) { return <div className="qm-export-row"><strong>{label}</strong><button className="target-select enabled" onClick={() => copy(`${label} Multi-Buy`, exports.eveMultiBuy)}>Copy Multi-Buy</button><button className="target-select enabled" onClick={() => copy(`${label} Discord`, exports.discordReport)}>Copy Discord</button><button className="target-select enabled" onClick={() => downloadFile(`doctrine-${selected}-${suffix}.csv`, exports.csv, "text/csv")}>Export CSV</button></div>; }
function Purchase({ label, lines }: { label: string; lines: ShoppingLine[] }) { const summary = lineSummary(lines); return <details className="qm-purchase"><summary>{label} · {summary.types} types · {formatQty(summary.units)} units · {isk(summary.cost)} · {formatVolume(summary.volume)} · {summary.unpriced} unpriced</summary>{lines.map(line => <div className="inv-row" key={line.typeId} style={{ gridTemplateColumns: "1.5fr .7fr .9fr .9fr 1fr" }}><div>{line.itemName}</div><div>{formatQty(line.shortageQuantity)}</div><div>{isk(line.totalAcquisitionCost)}</div><div>{formatVolume(line.totalVolumeM3)}</div><div>{line.marketStatus}</div></div>)}</details>; }
function DemandTable({ items }: { items: DoctrineItem[] }) { return <div className="inv-table qm-demand-table">{items.map(item => <details key={item.typeId}><summary className="inv-row qm-demand-grid"><div className="inv-name">{item.itemName}<span className="bts-result-meta">{item.itemKind}</span></div><div>Required {formatQty(item.required)}</div><div>Missing {formatQty(item.missing)}</div><div className={`inv-status ${item.action === "READY" ? "nominal" : item.action === "BUILD" ? "coolant" : "alert"}`}>{item.action}</div><div>{isk(item.purchaseCost)}</div><div>{formatVolume(item.totalMissingVolumeM3)}</div><div>{item.blockedReason === "Missing blueprint" ? "Missing Blueprint" : item.blockedReason ?? item.marketStatus}</div></summary><div className="data-source">{item.blockedDetail ?? item.marketStatus} · Owned {formatQty(item.owned)} · Reserved {formatQty(item.reserved)} · Available {formatQty(item.available)}</div></details>)}</div>; }
